### ISSUE TITLE
Removing unmaintained dependencies

### ISSUE THREAD

**Issue by Andrioshe** [Saphs/BrettSpiel#158]
I would like to consider removing unsupported, inactive or otherwise unmaintained packages from the dependencies.

The following are known to be superseded by supported or otherwise maintained variants:

markdown-to-html-pipe --> ngx-markdown

those packages could block further upgrades in the future.

**Comment by DanielLiebler** [comment]
markdown-to-html-pipe is now removed, but not yet replaced.
It will be replaced in the backend https://github.com/Saphs/BrettSpiel_Backend
refer to #166
