### ISSUE TITLE
Mülleimer

### ISSUE THREAD

**Issue by Saphs** [Saphs/BrettSpiel#32]
kronkorken mülleimer implementieren

**Comment by DanielLiebler** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mülleimer/neue Spieler an einem Client hinzufügen](https://trello.com/c/1zVBJRJ0/79-m%C3%BClleimer-neue-spieler-an-einem-client-hinzuf%C3%BCgen)
